### PR TITLE
new language added, used try and exception where required and as well…

### PR DESCRIPTION
**Pull request by SJ029626**
… as fixed the code

# Problem

Explain the context and why you're making that change.  What is the
problem you're trying to solve? In some cases there is not a problem
and this can be thought of being the motivation for your change.

So Some Coding languages were not present such as jython and Solidity and as well as try and except were not used in some functions. and fixed the 84>79 issues in some cases.

# Solution

Describe the modifications you've done.
So added all the things of the above problem.

# Result

What will change as a result of your pull request? Note that sometimes
this section is unnecessary because it is self-explanatory based on
the solution.
All is working as expected, but 2 new languages will be added which will help users to get more widen area and the try except in some functions can help to solve other problems as well.

### CODE REVIEW

**Comment by SJ029626** [comment]
@OrkoHunter you can merge the request now.

**Comment by OrkoHunter** [comment]
Hey @SJ029626 ! I don't have access to this repo anymore. But I approve of it. Someone from TwitterOSS team might be able to help you. :)

**Comment by SJ029626** [comment]
@twitter-service or anyone can merge the request

**Comment by SJ029626** [comment]
@grimreaper or @decause or @qix Whoever is seeing this repo please merge my PR. Please.

**Comment by grimreaper** [comment]
Thank you!

**Pull request merged**
